service: <%= projectName %>

frameworkVersion: ">=1.1.0 <2.0.0"

package:
  exclude:
    - artifacts/**
    - bin/**
    - test/**
    - .idea/**
    - .git/**
    - .editorconfig
    - .eslintrc.json
    - .gitattributes
    - .gitignore
    - .npmrc
    - jsdoc.conf
    - README.md
    - serverless.yml
    - yarn.lock
  include:
    - src/**
    - config/**
    - node_modules/**
    - package.json

provider:
  name: aws
  cfLogs: true
  runtime: nodejs4.3
  stage: dev
  region: eu-west-1
  memorySize: 128
  stackTags:
    squad: Test

functions:
### yeoman hook ###
## Don't touch this comment, the subgenerator needs it'

## Uncomment for dev purpose only.
## Re-comment it before deploy !!
#plugins:
#  - serverless-offline
#  - serverless-mocha-plugin
