service: <%= projectName %>

frameworkVersion: ">=1.1.0 <2.0.0"

package:
  exclude:
    - artifacts/**
    - bin/**
    - test/**
    - .idea/**
    - .git/**
    - .editorconfig
    - .eslintrc.json
    - .gitattributes
    - .gitignore
    - .npmrc
    - jsdoc.conf
    - README.md
    - serverless.yml
    - yarn.lock
  include:
    - src/**
    - config/**
    - node_modules/**
    - package.json

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev # Set the default stage used. Default is dev
  region: ue-west-1 # Overwrite the default region used. Default is us-east-1
  memorySize: 128 # Overwrite the default memory size. Default is 1024
  timeout: 10 # The default is 6
  stackTags: # Optional CF stack tags
    squad: Test

functions:
### yeoman hook ###
## Don't touch this comment, the subgenerator needs it'

## Uncomment for dev purpose only.
## Re-comment it before deploy !!
#plugins:
#  - serverless-offline
#  - serverless-mocha-plugin
