stages:
  - deploy

############ Deploy ############
publish:
  image: node:latest
  stage: deploy
  script:
    - echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
    - npm publish
  tags:
    - docker
  only:
    - tags
######################################
